apiVersion: v1
kind: Secret
metadata:
  name: fsmakkak8s-day-over-cluster-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
data:
  name: {{ .Values.clusterDayOver.name | b64enc }}
  server: {{ .Values.clusterDayOver.url | b64enc }}
  config: {{ include "argocd.gke-configuration" . | b64enc }}
