apiVersion: v1
kind: Secret
metadata:
  name: fsmakkak8s-cluster-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
data:
  name: {{ .Values.cluster.name | b64enc }}
  server: {{ .Values.cluster.url | b64enc }}
  config: {{ .Values.cluster.config }}
