{{- if .Values.projects.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: fsm-akka-4eyes-project
  namespace: argocd
spec:
  description: "Project for FSM Akka Four Eyes Event Sourcing Application"
  destinations:
    - namespace: fsmakka
      name: {{ .Values.cluster.name }}
      server: {{ .Values.cluster.url }}
    - namespace: feature-*
      name: {{ .Values.cluster.name }}
      server: {{ .Values.cluster.url }}
    - namespace: integration-*
      name: {{ .Values.cluster.name }}
      server: {{ .Values.cluster.url }}
    - namespace: release-*
      name: {{ .Values.cluster.name }}
      server: {{ .Values.cluster.url }}
    - namespace: bugfix-*
      name: {{ .Values.cluster.name }}
      server: {{ .Values.cluster.url }}
    - namespace: hotfix-*
      name: {{ .Values.cluster.name }}
      server: {{ .Values.cluster.url }}
  sourceNamespaces:
    - fsmakka
    - feature-*
    - integration-*
    - release-*
    - bugfix-*
    - hotfix-*
  sourceRepos:
    {{ toYaml .Values.projects.sourceRepos }}
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
{{- end -}}