{{- if .Values.projects.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: fsm-akka-4eyes-project
  namespace: argocd
spec:
  description: "Project for FSM Akka Four Eyes Event Sourcing Application"
  destinations:
    - namespace: fsmakka
      server: https://kubernetes.default.svc
    - namespace: nexus
      server: https://kubernetes.default.svc
    - namespace: feature-*
      server: https://kubernetes.default.svc
  sourceNamespaces:
    - fsmakka
    - nexus
    - feature-*
  sourceRepos:
    - "https://github.com/mehmetsalgar/Akka-Finite-State-Machine.git"
    - "https://github.com/mehmetsalgar/address-check.git"
    - "https://github.com/mehmetsalgar/credit-score.git"
    - "https://github.com/mehmetsalgar/fraud-prevention.git"
    - "https://github.com/mehmetsalgar/customer-relationship-adapter.git"
    - "https://sonatype.github.io/helm3-charts/"
    - "http://fsmakka.salgar.org/repository/fsm-akka-helm/"
    - "http://nexus-nexus-repository-manager.nexus:8081/repository/fsm-akka-helm/"
    - "https://github.com/mehmetsalgar/fsm-akka-dev-environment.git"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
{{- end -}}