{{- if .Values.projects.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: fsm-akka-4eyes-project
  namespace: argocd
spec:
  description: "Project for FSM Akka Four Eyes Event Sourcing Application"
  destinations:
    - namespace: fsmakka
      server: https://fsmakkaaks-dns-d9052bcd.hcp.germanywestcentral.azmk8s.io:443
    - namespace: feature-*
      server: https://fsmakkaaks-dns-d9052bcd.hcp.germanywestcentral.azmk8s.io:443
    - namespace: integration-*
      server: https://fsmakkaaks-dns-d9052bcd.hcp.germanywestcentral.azmk8s.io:443
    - namespace: release-*
      server: https://fsmakkaaks-dns-d9052bcd.hcp.germanywestcentral.azmk8s.io:443
    - namespace: bugfix-*
      server: https://fsmakkaaks-dns-d9052bcd.hcp.germanywestcentral.azmk8s.io:443
    - namespace: hotfix-*
      server: https://fsmakkaaks-dns-d9052bcd.hcp.germanywestcentral.azmk8s.io:443
  sourceNamespaces:
    - fsmakka
    - feature-*
    - integration-*
    - release-*
    - bugfix-*
    - hotfix-*
  sourceRepos:
    {{ toYaml .Values.sourceRepos }}
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
{{- end -}}