{{- if .Values.projects.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: fsm-akka-4eyes-project
  namespace: argocd
spec:
  description: "Project for FSM Akka Four Eyes Event Sourcing Application"
  destinations:
    - namespace: fsmakka
      server: https://kubernetes.default.svc
    - namespace: nexus
      server: https://kubernetes.default.svc
    - namespace: feature-*
      server: https://kubernetes.default.svc
  sourceNamespaces:
    - fsmakka
    - nexus
    - feature-*
  sourceRepos:
    {{ toYaml .Values.sourceRepos }}
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
{{- end -}}