projects:
  enabled: false

argo-cd:
  enabled: true

  dex:
    enabled: false
  controller:
    extraArgs:
      - --application-namespaces
      - "*"
  server:
    extraArgs:
      - --insecure
      - --application-namespaces
      - "*"
    config:
      repositories: |
        - name: nexus-repository-manager
          type: helm
          url: "https://sonatype.github.io/helm3-charts/"
        - name: k8ssandra
          type: helm
          url: "https://helm.k8ssandra.io/stable"
        - name: traefik
          type: helm
          url: "https://helm.traefik.io/traefik"
        - name: elasticsearch
          type: helm
          url: "https://helm.elastic.co/"
        - name: metrics-server
          type: helm
          url: "https://kubernetes-sigs.github.io/metrics-server/"
